main:
  freq: 600  # seconds between each check
  days_hist: 14  # number of days in the past to compare against
  n_std: 2.0  # number of standard deviations from the average before sending a message
  update_hour: 16  # what hour of the day to always send a message (between 0 and 23 inclusive)
